[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/soap-hiranmandi"
  to = "http://5.187.2.138/soap/SlotHiranmandiSOAP.dll/soap/IInBet"
  status = 200
  force = true

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
