[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/soap-hiranmandi"
  to = "http://5.187.2.138/soap/SlotHiranmandiSOAPFrame.dll/soap/IInBet"
  status = 200
  force = true

