import test from 'node:test';
import assert from 'node:assert/strict';
import {buildDoubleForm,mapDoubleResponse,sendDoubleRequest} from '../src/api/doubleApiClient.js';
import {mergeRuntimeConfig} from '../src/api/runtimeConfig.js';
const context={token:'test-token',gameId:'khiradmandi-makor',playerId:7};
const params={requestId:'double-1',idCard:'67062918',wasDouble:1,sum:1000,side:'left'};
test('double sends only the five documented form fields',()=>{assert.deepEqual(Object.fromEntries(buildDoubleForm(params,context)),{gameId:'36',requestId:'double-1',cardId:'67062918',wasDouble:'1',sum:'1000'});for(const sum of [-1,0,'bad',Infinity])assert.throws(()=>buildDoubleForm({...params,sum},context),{code:'CONFIGURATION_ERROR'});for(const wasDouble of [0,1.5,'bad'])assert.throws(()=>buildDoubleForm({...params,wasDouble},context),{code:'CONFIGURATION_ERROR'});});
test('double maps win and zero loss and rejects mismatched or malformed results',()=>{for(const WinSum of ['0',0,'2000',2000]){const result=mapDoubleResponse({idCard:params.idCard,WinSum},params);assert.equal(result.WinSum,Number(WinSum));assert.equal(result.status,Number(WinSum)>0?'win':'lose');assert.equal(result.requestId,params.requestId);assert.equal(result.WasDouble,1);assert.equal(result.side,'left');assert.equal(result.backendManagedWallet,true);}for(const WinSum of [undefined,null,'',false,-1,'bad'])assert.throws(()=>mapDoubleResponse({idCard:params.idCard,WinSum},params),{code:'BACKEND_RESPONSE_ERROR'});assert.throws(()=>mapDoubleResponse({idCard:'other',WinSum:'2000'},params),{code:'BACKEND_RESPONSE_ERROR'});});
test('double uses Bearer and never retries rejected or uncertain requests',async()=>{mergeRuntimeConfig({sessionApiBaseUrl:'https://example.invalid'});const original=globalThis.fetch;const body=buildDoubleForm(params,context);const options={token:context.token,requestId:params.requestId};let calls=0;try{globalThis.fetch=async(url,init)=>{calls++;assert.equal(url,'https://example.invalid/double');assert.equal(init.headers.Authorization,'Bearer test-token');assert.equal(init.body.has('token'),false);return new Response(JSON.stringify({idCard:params.idCard,WinSum:'0'}));};assert.equal((await sendDoubleRequest(body,options)).WinSum,'0');assert.equal(calls,1);globalThis.fetch=async()=>new Response(JSON.stringify({error_code:401,error:'Expired'}),{status:401});await assert.rejects(sendDoubleRequest(body,options),{code:'ACCESS_DENIED'});globalThis.fetch=async()=>new Response('broken');await assert.rejects(sendDoubleRequest(body,options),{code:'BACKEND_RESPONSE_ERROR'});calls=0;globalThis.fetch=async(_url,{signal})=>{calls++;return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('abort'),{name:'AbortError'}))));};await assert.rejects(sendDoubleRequest(body,{...options,timeoutMs:5}),{code:'TIMEOUT',requestId:'double-1'});assert.equal(calls,1);}finally{globalThis.fetch=original;}});
